---
#
# Ansible managed
#
repository:
  description: Install and configure rundeck on your system.
  homepage: https://buluma.github.io/
  topics: rundeck, ansible, molecule, tox, playbook, hacktoberfest
